server:
  port: 8080
  servlet:
    context-path: /EasyBuy
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.kgc.entity
spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easybuy?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: debug
replay:
  maxRandom: 10
  minRandom: 20
mail:
  host: smtp.qq.com
  username: 1348466224@qq.com
  password: cqvuubenttdsjecb


