server:
  port: 8080
  servlet:
    context-path: /EasyBuy
mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easybuy?characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com
    username: 1348466224@qq.com
    password: cqvuubenttdsjecb


